version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-build  # Use the frontend build stage
    ports:
      - "3000:3000"  # Expose frontend on port 3000
    environment:
      - NODE_ENV=production  # Set the environment to production

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend  # Use the backend stage
    ports:
      - "5000:5000"  # Expose backend on port 5000
    environment:
      FLASK_APP: main.py  # Specify the Flask entry point
      FLASK_ENV: development  # Set the Flask environment
    volumes:
      - ./sre-backend:/app/backend  # Mount the backend code to allow live reloads during development

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"    # phpMyAdmin on port 8081
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  db_data:
